FROM golang:1.6

# Install glide - dependencies manager.
RUN mkdir /tools
WORKDIR /tools
RUN wget https://github.com/Masterminds/glide/releases/download/0.10.2/glide-0.10.2-linux-386.tar.gz
RUN tar -zxvf glide-0.10.2-linux-386.tar.gz
RUN mv linux-386/ glide/
ENV PATH /tools/glide:$PATH

# Add project
ADD ./ /go/src/github.com/improwised/cantaloupe
WORKDIR /go/src/github.com/improwised/cantaloupe

# Install Dependencies.
RUN glide up

# Expose the application on port 8000
EXPOSE 8000

# Build application.
RUN go build

# Run exec generated by build to start project.
CMD ["./cantaloupe"]
