# go with glide dependecy manager
FROM cgoes/goglide

# Add project
ADD ./ /go/src/github.com/improwised/cantaloupe
WORKDIR /go/src/github.com/improwised/cantaloupe

# Install Dependencies.
RUN glide up

# Expose the application on port 8000
EXPOSE 8000

# Build application.
RUN go build

# Run exec generated by build to start project.
CMD ["./cantaloupe"]
