version: '2'
services:
  db:
    image: postgres:9.6-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123123
      POSTGRES_USER: postgres
      POSTGRES_DB: cantaloupe
    volumes:
      - ./postgres_data:/var/lib/postgresql/data




