 export const SET_FIELDS = 'SET_FIELDS';

//constants for performing actions releted to 'USERS' ...
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_FAILULER = 'ADD_USER_FAILULER';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILULER = 'FETCH_USERS_FAILULER';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAILULER = 'EDIT_USER_FAILULER';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILULER = 'DELETE_USER_FAILULER';

//constants for performing actions releted to 'MACHINES' ...
export const FETCH_MACHINES_SUCCESS = 'FETCH_MACHINES_SUCCESS';
export const FETCH_MACHINES_FAILULER = 'FETCH_MACHINES_FAILULER';
export const FETCH_MACHINES_INFORMATION_SUCCESS = 'FETCH_MACHINES_INFORMATION_SUCCESS';
export const FETCH_MACHINES_INFORMATION_FAILULER = 'FETCH_MACHINES_INFORMATION_FAILULER';
export const EDIT_MACHINE_SUCCESS = 'EDIT_MACHINE_SUCCESS';
export const EDIT_MACHINE_FAILULER = 'EDIT_MACHINE_FAILULER';
export const DELETE_MACHINE_SUCCESS = 'DELETE_MACHINE_SUCCESS';
export const DELETE_MACHINE_FAILULER = 'DELETE_MACHINE_FAILULER';

//constants for performing actions releted to 'COMPONENTS' ...
export const FETCH_COMPONENTS_SUCCESS = 'FETCH_COMPONENTS_SUCCESS';
export const FETCH_COMPONENTS_FAILULER = 'FETCH_COMPONENTS_FAILULER';
export const EDIT_COMPONENT_SUCCESS = 'EDIT_COMPONENT_SUCCESS';
export const EDIT_COMPONENT_FAILULER = 'EDIT_COMPONENT_FAILULER';
export const DELETE_COMPONENT_SUCCESS = 'DELETE_COMPONENT_SUCCESS';
export const DELETE_COMPONENT_FAILULER = 'DELETE_COMPONENT_FAILULER';
export const FETCH_COMPONENT_INFORMATION_SUCCESS = 'FETCH_COMPONENT_INFORMATION_SUCCESS';
export const FETCH_COMPONENT_INFORMATION_FAILULER = 'FETCH_COMPONENT_INFORMATION_FAILULER';
export const FILTER_COMPONENTS_SUCCESS = 'FILTER_COMPONENTS_SUCCESS';
export const FILTER_COMPONENTS_FAILULER = 'FILTER_COMPONENTS_FAILULER';

//constants for performing actions releted to 'INVOICES' ...
export const FETCH_INVOICES_SUCCESS = 'FETCH_INVOICES_SUCCESS';
export const FETCH_INVOICES_FAILULER = 'FETCH_INVOICES_FAILULER';
export const EDIT_INVOICE_SUCCESS = 'EDIT_INVOICE_SUCCESS';
export const EDIT_INVOICE_FAILULER = 'EDIT_INVOICE_FAILULER';
export const DELETE_INVOICE_SUCCESS = 'DELETE_INVOICE_SUCCESS';
export const DELETE_INVOICE_FAILULER = 'DELETE_INVOICE_FAILULER';
export const SET_FIELDS_INVOICES = 'SET_FIELDS_INVOICES';
export const SET_FIELDS_INVOICES_COMPONENT = 'SET_FIELDS_INVOICES_COMPONENT';
export const FETCH_ONE_INVOICE_SUCCESS = 'FETCH_ONE_INVOICE_SUCCESS';
export const FETCH_ONE_INVOICE_FAILULER = 'FETCH_ONE_INVOICE_FAILULER';

//constants for performing actions releted to 'INCIDENTS' ...
export const FETCH_INCIDENTS_SUCCESS = 'FETCH_INCIDENTS_SUCCESS';
export const FETCH_INCIDENTS_FAILULER = 'FETCH_INCIDENTS_FAILULER';
export const EDIT_INCIDENT_SUCCESS = 'EDIT_INCIDENT_SUCCESS';
export const EDIT_INCIDENT_FAILULER = 'EDIT_INCIDENT_FAILULER';
export const DELETE_INCIDENT_SUCCESS = 'DELETE_INCIDENT_SUCCESS';
export const DELETE_INCIDENT_FAILULER = 'DELETE_INCIDENT_FAILULER';

//constants for performing actions releted to 'CATEGORY' ...
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_FAILULER = 'ADD_CATEGORY_FAILULER';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILULER = 'FETCH_CATEGORIES_FAILULER';
export const EDIT_CATEGORY_SUCCESS = 'EDIT_CATEGORY_SUCCESS';
export const EDIT_CATEGORY_FAILULER = 'EDIT_CATEGORY_FAILULER';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAILULER = 'DELETE_CATEGORY_FAILULER';
