# Canaloupe - API Documentation

# Cantaloupe

Cantaloupe is an asset tracking system to deals with the components and easily keep its records.

:[Users](/users.apib)

:[Machines](/machines.apib)

:[Invoices](/invoices.apib)

:[Incidents](/incidents.apib)

:[Components](/components.apib)