# Canaloupe - API Documentation

## Cantaloupe

Cantaloupe is an asset tracking system to deals with the components and easily keep its records.

## Error States
The common [HTTP Response Status Codes](https://github.com/for-GET/know-your-http-well/blob/master/status-codes.md) are used.

:[Users](/users.apib)

:[Machines](/machines.apib)

:[Invoices](/invoices.apib)

:[Incidents](/incidents.apib)

:[Components](/components.apib)