# Group Components

- **id** : Id of Component(string, Required)
- **name** : Name of Component(string, Required)
- **inv_id** : Id of Invoice(string, Required)
- **warranty_till** : Warranty of Component(string, Required)
- **desc** : Description(string, Optional)
- **active** : Component is acti(string, Required)ve or not
- **deleted_at** : Deleted Timestamp of Component(string, Optional)
- **created_at** : Created Timestmp of Component(string, Optional)

## Display Components [/components{?active}]

Display All Components

### Display Components [GET]

+ Parameters
    + active : false - Display all Components. On true it will display only active Components.
              By default it will display active Components only.

+ Response 201


	+ Body

	    	[{
	    		id : `1`,
	    		name : `Mouse`,
	    		inv_id : `1`,
	    		warranty_till : `12-04-2017`,
	    		desc : `description of mouse`,
	    		active : `true`,
	    		delted_at : ``
	    		created_at : `08-08-2016T12:12:12`
	    	}]

