# Group Components

- **id** : Id of Component(string, Required)
- **name** : Name of Component(string, Required)
- **invoice_id** : Id of Invoice(string, Required)
- **warranty_till** : Warranty of Component(string, Required)
- **description** : Description(string, Optional)
- **active** : Component is active(string, Required) or not
- **deleted_at** : Deleted Timestamp of Component(string, Optional)
- **created_at** : Created Timestmp of Component(string, Optional)

## Display Components [/components{?all}]

Display All Components

### Display Components [GET]

+ Parameters
    + all : true - Display all Components. On false it will display only active Components.
              By default it will display active Components only.

+ Response 200 (application/json)

    + Headers

    + body

            [{
            "id": 1,
            "serial_no":"12SOECE11230",
            "name": "Mouse",
            "invoice_id": 1,
            "warranty_till": "12-04-2017 ",
            "description": "description of mouse",
            "active": true,
            "deleted_at":"08-08-2016T12:12:12"
            }]



