# Group  Incidents

- **id** : id of incident(string, Required)
- **component_id** : id of incident on which incident happened(string, Required)
- **title** : Brief title of incident(string, Required)
- **description** : Entire description of incident (string, Optional)
- **status** : status of comonent whether its in process or not(string, Required)
- **resolved_at** : Timestamp of resolved component(string, Required)
- **created_at** : Timestamp when incedent happened(string, Required)

## All Incidents [/incidents]

Display All Incidents.

### List All Incidents [GET]

+ Response 200 (application/json)

    + Headers

            Link: "host:port/incidents"

    + Body

            [{
                id : `1`
                component_id : `1`
                title : `Component Damaged`
                description : `component damaged Due to power cut`
                status : `active`
                resolved_at : ` `
                created_at : `2016-08-08T02:15:15Z`
            }]


## Add New Incident [/incident]

### Add New Incident[POST]

+ Request (application/json)

    + Attributes
        + component_id: `1`
        + incident_title: `Component Damaged`
        + description: `Component damaged Due to power cut`

+ Response 201 (application/json)

    + Headers

            Link: "host:port/incidents"

## Edit incident [/incidents{?id}]

### Edit incident[PATCH]

+ Parameters
    + id: 1 - Id of incident to be update

+ Request (application/json)

    + Body

            + component_id: `1`,
            + incident_title: `Component Damaged`,
            + description: `Component damaged Due to power cut`

+ Response 200 (application/json)

    + Headers

            Link: "host:port/incidents{?id}"

## Delete Incident [/incidents{?incident_id}]

### Delete Incident[DELETE]

+ Parameters
    +  incident_id : 1 - id of incident to delete

+ Request (application/json)

+ Response 200 (application/json)

    + Headers

            Link: "host:port/incidents{?incident_id}"

## Display Incident For Edit [/incidents{?incident_Id}]

### Display Incident For Edit[GET]

+ Parameters
    + incident_Id : 1 - Id of incident to display

+ Request (application/json)

+ Response 200 (application/json)

    + Headers

            Link: "host:port/incidents{?incident_Id}"

    + Body

            {
                id : `1`
                component_id : `1`
                title : `Component Damaged`
                description : `component damaged Due to power cut`
                status : `active`
                resolved_at : ` `
                created_at : `2016-08-08T02:15:15Z`
                modified_at : ` `
            }

