# Group Machines

perform different machines releated operations.

- **id** : id of machine(string, Required)
- **name** : Name Of Machine(string, Required)
- **component_id** : Id of Component(string, Required)
- **component_name** : Name of Component(string, Required)
- **user** : Name Of User(string, Required)
- **deleted_at** : Deleted Timesramo of Machine(string, Optional)

## All Machines [/machines{?all}]

Display All Machines.

+ Parameters
    + all: true - Either Display all Machines or only active Machines. true for all machines and false for active machines only.
               By Default active machines will be display

### List All Machines [GET]

+ Response 200 (application/json)

    + Headers

    + Body

            [{
                "id" : "1",
                "name" : "mako",
                "user" : "Ashivn",
                "deleted_at" : "2016-08-08T02:15:15Z"
            }]

## Add New Machine [/machines]

### Add New Machine[POST]

+ Request (application/json)

    + Attributes
        + name: `mako`

+ Response 201

## Edit Machine [/machines/{machine_id}]

### Edit Machine[PATCH]

+ Parameters
    + machine_id: 2 - Id of machine to be update

+ Request (application/json)

    + Attributes
        + name: `Thor`

+ Response 200

### Delete Machine[DELETE]

+ Parameters
    + machine_id : 1 - Id of machine to be delete

+ Response 204

### Display One Machine Info [GET]

+ Parameters
    + machine_id : 3 - Id of machine to display information of it.

+ Response 200 (application/json)

    + Headers

    + Body

            {
                "id" : 1,
                "name" : "mako",
                "user" : "Ashvin",
                "deleted_at" : "2016-08-08T02:15:15Z"
            }

## Display All Components With Machine [/machines/{machine_id}/components{?all}]

Display Machine Components.

+ Parameters
    + all : true - Display all components included deleted components. On false it will display only active components.
              By default it will display active components only.
    + machine_id : 1 - Id of Machine to Display Components

### Display Components [GET]

+ Response 200 (application/json)

    + Headers

    + body

            {
                "id" : "1",
                "machine_id" : "1",
                "name" : "mako",
                "components":[{
                                "id" : 1,
                                "name" : "Mouse",
                                "deleted_at" : "2016-08-08T02:15:15Z"
                }]
            }

## Add Component to machine [/machines/{machine_id}/components]

+ Parameters
    + machine_id : 1 - Id of Machine

### Add Component to Machine [POST]

+ Request (application/json)

    + Attributes
        + information
            + id : `1`
            + machine_id : `2`
            + name : `mako`
            + components_id : 2 (array)
            + components_name : `MotherBoard` (array)

+ Response 201

## Remove Component From Machine [/machines/{machine_id}/components/{component_id}]

+ Parameters
    + machine_id : 1 - Id of Machine
    + component_id : 1 - id of Component

### Remove Component From Machine [DELETE]

+ Parameters
    + component_id : 1 - Id to Remove Component From Machine.

+ Response 204

## Assign Machine to User [/machines/{machine_id}/users/{user_id}]

### Remove User From Machine[DELETE]

+ Parameters
    +  user_id : 1 - id of user to Remove Machine
    +  machine_id : 2 - id of Machine

+ Response 204
