# Group Machines

perform different machines releated operations.

- **id** : id of machine(string, Required)
- **machine_name** : Name Of Machine(string, Required)
- **created_at** : Created Timestamp of Machine(string, Required)
- **deleted_at** : Deleted Timesramo of Machine(string, Optional)

## All Machines [/machines{?active}]

Display All Machines.

+ Parameters
    + active: false - Either Display all Machines or only active Machines. false for all machines and true for active machines only.
               By Default active machines will be display

### List All Machines [GET]

+ Response 200 (application/json)

    + Headers

            Link: "host:port/machines{?active}"

    + Body

            [{
                id : `1`,
                machine_name : `mako`,
                created_at : `2016-08-08T02:15:15Z`,
                deleted_at : ` `
            }]

## Add New Machine [/machines]

### Add New Machine[POST]

+ Request (application/json)

    + Attributes
        + machine_name: `mako`

+ Response 201 (application/json)

    + Headers

            Link: "host:port/machines"

## Edit Machine [/machines{?id}]

### Edit Machine[PATCH]

+ Parameters
    + id: 2 - Id of machine to be update

+ Request (application/json)

+ Response 200 (application/json)

    + Headers

            Link: "host:port/machines{?id}"

## Delete Machine [/machines{?machine_id}]

### Delete Machine[DELETE]

+ Parameters
    + machine_id : 1 - Id of machine to be delete

+ Request (application/json)

+ Response 200 (application/json)

    + Headers

            Link: "host:port/machine{?machine_id}"

## Display Machine Info For Edit [/machines{?machine_Id}]

### Display Machine Info For Edit[GET]

+ Parameters
    + machine_Id : 3 - Id of machine to display information of it.

+ Request (application/json)

+ Response 200 (application/json)

    + Headers1

            Link: "host:port/machines{?machine_Id}"


    + Body

            {
                id : `1`,
                machine_name : `mako`,
                created_at : `2016-08-08T02:15:15Z`,
                deleted_at : ` `
            }

