# Group Users

perform different user releated operations.

- **id** : id of user(string, Required)
- **user_name** : Name Of User(string, Required)
- **company_email** : Company Email Id Of User(string, Required)
- **created_at** : Created Timestamp of User(string, Required)
- **deleted_at** : Deleted Timesramo of User(string, Required)

## All Users [/users{?active}]

Display All Users.

+ Parameters
    + active : false - Display all Users. On true it will display only active users.
              By default it will display active users only.

### List All User [GET]

+ Response 200 (application/json)

    + Headers

    + body

            [{
            id : `2`,
            user_name : `ashvin`,
            company_email : `ashvin@improwised.com`,
            created_at : `2016-08-08T02:15:15Z`,
            deleted_at : ` `
            }]

## Add New User [/users]

### Add New User[POST]

+ Request (application/json)

    + Attributes
        + user_name: `Ashvin Kumbhani`
        + company_email: `ashvin@improwised.com`

+ Response 201

## Edit User [/users{?user_id}]

### Edit User[PATCH]

+ Parameters
    + user_id : 1 - Id of user whose information wants to update.

+ Request (application/json)

    + Attributes
        + user_name: `Ashvin Kumbhani`
        + company_email: `ashvin@improwised.com`

+ Response 200

## Delete User [/users{?users_id}]

### Delete User[DELETE]

+ Parameters
    + users_id : 1 - Id of user wants to remove.

+ Response 204

## Display User For Edit [/users{?user_Id}]

### Display User For Edit[GET]

+ Parameters
    + user_Id: 1 - Id of user whose information wants to display.

+ Request (application/json)

+ Response 200 (application/json)

    + Headers

    + Body

            {
            id : `1`
            user_name : `ashvin`
            company_email : `ashvin@improwised.com`
            created_at : `2016-08-08T02:15:15Z`
            deleted_at : ` `
            }


