# Group Users

perform different user releated operations.

## Error States
The common [HTTP Response Status Codes](https://github.com/for-GET/know-your-http-well/blob/master/status-codes.md) are used.

## Atributes
- **id** : id of user(Required, int)
- **user_name** : Name Of User(Required, string)
- **company_email** : Company Email Id Of User(Optional, string)
- **created_at** : Created Timestamp of User(Required, string)
- **deleted_at** : Deleted Timesramo of User(Required, string)

## All Users [/users?active=false]

Display All Users.

+ Parameters
    + active: false - Display all Users. On true it will display only active users.
              By default it will display active users only.

### List All User [GET]

+ Response 200 (application/json)

    + Headers

            Link: "host:port/users?active=true"

    + body

            [{
            id : "1"
            user_name : "ashvin"
            company_email : "ashvin@improwised.com"
            created_at : "10/08/2016:12:12:12"
            deleted_at : ""
            }]

## Add New User [/users]

### Add New User[POST]

+ Request (application/json)

    + user_name:false - Display all Users.on true it will display only active users.
              By default it will display active users only.

    + Attributes
        + user_name: `Ashvin Kumbhani`
        + company_email: `ashvin@improwised.com`

+ Response 201 (application/json)

    + Headers

            Link: "host:port/users"

## Edit User [/users?id={id}]

### Edit User[PATCH]

+ Parameters
    + id: 1 - Id of user whose information wants to update.

+ Request (application/json)

    + Attributes
        + user_name: `Ashvin Kumbhani`
        + company_email: `ashvin@improwised.com`

+ Response 200 (application/json)

    + Headers

            Link: "host:port/user?id={id}"

## Delete User [/users?id={user_id}]

### Delete User[DELETE]

+ Parameters
    + user_id: 1 - Id of user wants to remove.

+ Request (application/json)

+ Response 200 (application/json)

    + Headers

            Link: "host:port/users?id={user_id}"

## Display User For Edit [/users?id={users_id}]

### Display User For Edit[GET]

+ Parameters
    + users_id: 1 - Id of user whose information wants to display.

+ Request (application/json)

+ Response 200 (application/json)

    + Headers

            Link: "host:port/users?id={users_id}"

    + Body

            {
            id : "1"
            user_name : "ashvin"
            company_email : "ashvin@improwised.com"
            created_at : "10/08/2016:12:12:12"
            deleted_at : ""
            }


