# Group Users

perform different user releated operations.

- **id** : id of user(string, Required)
- **name** : Name of User(string, Required)
- **machine_id** : Id of Machine(string, required)
- **machine_name** : Name of Machine(string, optional)
- **company_email** : Company Email Id of User(string, Required)
- **deleted_at** : Deleted Timesramo of User(string, Required)

## All Users [/users{?all}]

Display All Users.

+ Parameters
    + all : true - Display all Users. On false it will display only active users.
              By default it will display active users only.

### List All User [GET]

+ Response 200 (application/json)

    + Headers

    + body

            [{
            "id": 1,
            "name": "ashvin",
            "company_email": "ashvin @improwised.com ",
            "machine_id" : 1,
            "machine_name" : "mako",
            "deleted_at": "2016-08-08T02:15:15Z"
            }]

## All Users [/users]

### Add New User[POST]

+ Request (application/json)

    + Attributes
        + name: `Ashvin Kumbhani`
        + company_email: `ashvin@improwised.com`
        + machine_id: `1`

+ Response 201

    + body

            {
                "id" : 1,
                "name" : "ashvin",
                "company_email" : "ashvin@improwised.com",
                "machine_id" : 1,
                "machine_name" : "mako"
            }


## Edit User [/users/{user_id}]

### Edit User[PATCH]

+ Parameters
    + user_id : 1 - Id of user whose information wants to update.

+ Request (application/json)

    + Attributes
        + name: `Ashvin Kumbhani`
        + company_email: `ashvin@improwised.com`
        + machine_id: `1`

+ Response 200

### Delete User[DELETE]

+ Parameters
    + user_id : 1 - Id of user wants to remove.

+ Response 204

### Display One User[GET]

+ Parameters
    + user_id: 1 - Id of user whose information wants to display.

+ Response 200 (application/json)

    + Headers

    + Body

            {
            "id": 1,
            "name": "ashvin",
            "machine_id": 1,
            "machine_name" : "mako",
            "company_email": "ashvin @improwised.com ",
            "deleted_at": "2016-08-08T02:15:15Z"
            }




